[package]
name = "linear_least_squares"
version = "0.1.0"
edition = "2021"

[dependencies]
rand_distr = "0.4"
rand = "0.8"
nalgebra = { version = "0.33", features = ["rand"] }
clap = { version = "4.5.19", features = ["derive"] }

[[bin]]
name = "linear_least_squares"
path = "src/main.rs"
